/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package designs;
import broker.DatabaseConnection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Windows HD
 */
public class UnosStudenta extends javax.swing.JFrame {

    /**
     * Creates new form UnosStudenta
     */
    public UnosStudenta() throws SQLException {
    
        initComponents();
        Connection con = DatabaseConnection.getInstance();
        Statement st = con.createStatement();
        String sql = "SELECT Naziv FROM SMER";
        ResultSet rs = st.executeQuery(sql);
        while(rs.next()){
            String naziv = rs.getString("Naziv");
            smerComboBox.addItem(naziv);
        }
        
        
        
        rs.close();
        st.close();
        con.close();
    
    }
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imetxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        indekstxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telefontxt = new javax.swing.JTextField();
        godinaStudijaComboBox = new javax.swing.JComboBox<>();
        smerComboBox = new javax.swing.JComboBox<>();
        budzetCheckBox = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        modulComboBox = new javax.swing.JComboBox<>();
        DodajBtn = new javax.swing.JButton();
        stepenStudijaComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        prezimetxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unos studenta");
        setName("unosStudenta"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ime:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel2.setText("Prezime:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));
        getContentPane().add(imetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 71, -1));

        jLabel3.setText("Broj indeksa:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel4.setText("Email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));
        getContentPane().add(indekstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 71, -1));

        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });
        getContentPane().add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 71, -1));

        jLabel5.setText("Telefon:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        getContentPane().add(telefontxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 71, -1));

        godinaStudijaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        godinaStudijaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                godinaStudijaComboBoxActionPerformed(evt);
            }
        });
        godinaStudijaComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                godinaStudijaComboBoxPropertyChange(evt);
            }
        });
        getContentPane().add(godinaStudijaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 50, 20));

        smerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smerComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(smerComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        budzetCheckBox.setText("budzet");
        getContentPane().add(budzetCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 85, -1));

        jLabel6.setText("Godina studija:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel7.setText("Smer:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jLabel8.setText("Modul:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        modulComboBox.setEnabled(false);
        getContentPane().add(modulComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        DodajBtn.setText("Dodaj studenta");
        DodajBtn.setEnabled(false);
        DodajBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DodajBtnMouseEntered(evt);
            }
        });
        DodajBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodajBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DodajBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 188, 71));

        stepenStudijaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(stepenStudijaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 50, 20));

        jLabel9.setText("Stepen studija:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));
        getContentPane().add(prezimetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 71, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void godinaStudijaComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_godinaStudijaComboBoxPropertyChange

    }//GEN-LAST:event_godinaStudijaComboBoxPropertyChange

    private void godinaStudijaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_godinaStudijaComboBoxActionPerformed
        // TODO add your handling code here:
        if(!godinaStudijaComboBox.getSelectedItem().equals("1")){
            System.out.println("radi");
            modulComboBox.setEnabled(true);
        }
        else{
            modulComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_godinaStudijaComboBoxActionPerformed

    private void smerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smerComboBoxActionPerformed
        // TODO add your handling code here:
        modulComboBox.removeAllItems();
        if(smerComboBox.getSelectedItem().equals("Informacioni sistem i tehnologije")){
            try {
                Connection con = DatabaseConnection.getInstance();
                Statement st = con.createStatement();
                String sql = "SELECT naziv FROM MODUL WHERE FKSmera=1";
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    String naziv = rs.getString("Naziv");
                    modulComboBox.addItem(naziv);
                }   } catch (SQLException ex) {
                Logger.getLogger(UnosStudenta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            try {
                Connection con = DatabaseConnection.getInstance();
                Statement st = con.createStatement();
                String sql = "SELECT naziv FROM MODUL WHERE FKSmera=2";
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    String naziv = rs.getString("Naziv");
                    modulComboBox.addItem(naziv);
                }   } catch (SQLException ex) {
                Logger.getLogger(UnosStudenta.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }//GEN-LAST:event_smerComboBoxActionPerformed

    private void DodajBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodajBtnActionPerformed
        // TODO add your handling code here:
            try {
                Connection con = DatabaseConnection.getInstance();
                String sql="INSERT INTO student(ime,prezime,brojIndeksa,email,telefon,stepenStudija,godinaStudija,FKModula,budzet,FKSmera) VALUES(?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement st = con.prepareStatement(sql);
                st.setLong(1, 9);
                st.setString(1, imetxt.getText());
                st.setString(2, prezimetxt.getText());  
                st.setString(3, indekstxt.getText());
                st.setString(4, emailtxt.getText());
                st.setString(5, telefontxt.getText());
                st.setInt(6, Integer.parseInt(stepenStudijaComboBox.getSelectedItem().toString()));  
                st.setInt(7, Integer.parseInt(godinaStudijaComboBox.getSelectedItem().toString()));
                
                String sql2="SELECT PKSmera FROM smer WHERE Naziv = ?";
                PreparedStatement st2 = con.prepareStatement(sql2);
                String pom = smerComboBox.getSelectedItem().toString();
                st2.setString(1, pom);
                ResultSet rs2 = st2.executeQuery();
                rs2.next();
                Long smer = rs2.getLong("PKSmera");
                
                String sql3="SELECT PKModula FROM modul WHERE naziv = ?";
                PreparedStatement st3 = con.prepareStatement(sql3);
                String pom3 = modulComboBox.getSelectedItem().toString();
                st3.setString(1, pom3);
                ResultSet rs3 = st3.executeQuery();
                rs3.next();
                Long modul = rs3.getLong("PKModula");
                
                st.setLong(8,modul);
                st.setBoolean(9, budzetCheckBox.isSelected());
                st.setLong(10, smer);
                st.executeUpdate();
                st.close();
                st2.close();
                st3.close();
                con.close();
                this.setVisible(false);
                } catch (SQLException ex) {
                Logger.getLogger(UnosStudenta.class.getName()).log(Level.SEVERE, null, ex);
            } 
    }//GEN-LAST:event_DodajBtnActionPerformed

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void DodajBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DodajBtnMouseEntered
        // TODO add your handling code here:
        if(!imetxt.getText().equals("") && !prezimetxt.getText().equals("") 
        && !indekstxt.getText().equals("") && !emailtxt.getText().equals("") 
        && !telefontxt.getText().equals("")){
            DodajBtn.setEnabled(true);
        }
        else{
            DodajBtn.setEnabled(false);
        }
    }//GEN-LAST:event_DodajBtnMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DodajBtn;
    private javax.swing.JCheckBox budzetCheckBox;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JComboBox<String> godinaStudijaComboBox;
    private javax.swing.JTextField imetxt;
    private javax.swing.JTextField indekstxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> modulComboBox;
    private javax.swing.JTextField prezimetxt;
    private javax.swing.JComboBox<String> smerComboBox;
    private javax.swing.JComboBox<String> stepenStudijaComboBox;
    private javax.swing.JTextField telefontxt;
    // End of variables declaration//GEN-END:variables
}
